import type { VercelRequest, VercelResponse } from "@vercel/node";

// AUTO-GENERATED — run: node scripts/generate-api-functions.mjs
// Data inlined from server.ts — no external imports needed
const DATA = [
{
    id: "1", slug: "k-home-cityview-ho-nai", title: "K-Home CityView Biên Hòa",
    location: "Đường Điều Xiển, Phường Hố Nai, TP. Biên Hòa, Đồng Nai",
    type: "Căn hộ nhà ở xã hội", price: "Từ 950 Triệu", priceNumber: 0.95, area: "47,3m² - 84,4m²",
    image: "/k-home cityview/V34_TAN-HOA_EXT_FACADE_FINAL_2.webp",
    description: "Tọa lạc tại Phường Hố Nai, TP. Biên Hòa, K-Home CityView là dự án nhà ở xã hội quy mô 2,85 hecta với 1.352 căn hộ và 30 căn shophouse, tiêu chuẩn thiết kế Singapore.",
    longDescription: "**Tổng quan dự án K-Home CityView Biên Hòa**\n\n**K-Home CityView** là dự án nhà ở xã hội (NOXH) phân khúc chất lượng cao, tọa lạc ngay tại mặt tiền **đường Điểu Xiển**, thuộc **Phường Hố Nai, Thành phố Biên Hòa, Tỉnh Đồng Nai**. Được quy hoạch trên tổng diện tích quỹ đất rộng **2,85 ha**, dự án kiến tạo một không gian sống văn minh, hiện đại và là giải pháp an cư lạc nghiệp hoàn hảo cho hàng ngàn hộ gia đình đang sinh sống và làm việc tại thủ phủ công nghiệp Đồng Nai.\n\nDự án sở hữu quy mô đồng bộ bao gồm **4 tòa tháp chung cư cao tầng** vững chãi. Với thiết kế tối ưu, K-Home CityView cung ứng ra thị trường nguồn cung dồi dào với hơn **1.300 căn hộ xã hội** giá hợp lý, kết hợp cùng hệ thống **căn hộ thương mại** và chuỗi **shophouse khối đế** sầm uất, đáp ứng trọn vẹn mọi nhu cầu từ an cư thuần túy đến kinh doanh dịch vụ.\n\n**Kiến trúc Singapore và đối tác chiến lược**\n\nMột trong những điểm nhấn vượt trội giúp K-Home CityView khác biệt hoàn toàn so với các dự án nhà ở xã hội thông thường chính là ngôn ngữ kiến trúc. Dự án được quy hoạch và thiết kế theo **tiêu chuẩn Singapore** hiện đại bởi các đơn vị tư vấn hàng đầu, mang đến diện mạo tinh tế, tối giản nhưng vô cùng tối ưu công năng. Các căn hộ tại đây đều sở hữu mặt thoáng lớn, đón trọn ánh sáng tự nhiên và gió trời thông thoáng.\n\nSự chỉn chu trong từng đường nét xây dựng được bảo chứng bởi sự đồng hành của các đối tác uy tín như **Global Vireon Studio**, **Kiến Trúc Việt**, **CDC Jsc** và **K-City**. Nhờ sự hợp tác chiến lược này, không gian kiến trúc của K-Home CityView không chỉ đạt tính thẩm mỹ cao mà còn đáp ứng nghiêm ngặt các tiêu chuẩn về **công trình xanh**, kiến tạo môi trường sống bền vững và tiết kiệm năng lượng cho cư dân.\n\n**Hệ sinh thái tiện ích nội khu đẳng cấp**\n\nVượt lên trên định nghĩa về một khu nhà ở thông thường, K-Home CityView được đầu tư đồng bộ hệ thống hạ tầng tiện ích nội khu khép kín nhằm nâng tầm chất lượng sống cho cộng đồng cư dân. Ngay trong lòng dự án, cư dân có thể tận hưởng không gian thư giãn lý tưởng tại **hồ bơi hiện đại**, giúp giải tỏa căng thẳng sau những giờ làm việc mệt mỏi.\n\nBên cạnh đó, các gia đình trẻ hoàn toàn yên tâm về không gian phát triển của con nhỏ với **khu vui chơi, sân chơi trẻ em** được thiết kế an toàn và sáng tạo. Dự án cũng chú trọng phát triển thể chất cho mọi lứa tuổi thông qua **khu thể dục thể thao ngoài trời** với hệ thống máy tập đa năng, cùng **nhà sinh hoạt cộng đồng** rộng rãi – nơi gắn kết tình cảm xóm giềng và tổ chức các hoạt động văn hóa tập thể.",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d946.1114524333827!2d106.9022019!3d10.9592617!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174dd0052a72139%3A0xd752da458a5eca9e!2zTk9YSCBI4buRIE5haQ!5e1!3m2!1sen!2s!4v1784801484940!5m2!1sen!2s",
    gallery: [
      "/k-home cityview/V34_TAN-HOA_EXT_FACADE_FINAL_2.webp",
      "/k-home cityview/V02_TAN-HOA_EXT_BBQ-GARDEN_FN_2-1.webp",
      "/k-home cityview/TAN-HOA_AERIAL_1_DRAFT-3_2-1.webp",
      "/k-home cityview/V03_TAN-HOA_EXT_NOXH_KID-PLAYGROUND_FINAL_2-1.webp",
      "/k-home cityview/V32_TAN-HOA_EXT_AERIAL_2_FINAL_2.webp",
      "/k-home cityview/V11_TH_EXT_NOTM_POOL_2.webp",
      "/k-home cityview/V12_TH_EXT_NOXH_POOL_2.webp",
      "/k-home cityview/V35_TAN-HOA_EXT_NOXH_POOL2_2.jpg",
      "/k-home cityview/V10_TH_EXT_GARDEN_FINAL_2.webp",
      "/k-home cityview/V08_TH_EXT_NOTM_SAN-VUON_FINAL_2.webp",
      "/k-home cityview/V09_TH_EXT_STREET-VIEW_FINAL_2.webp",
      "/k-home cityview/V07_TH_EXT_NOXH_KHOI-DE_FINAL_2-1.webp",
      "/k-home cityview/V36_TAN-HOA_EXT_NOXH_PARK_FINAL_2.jpg",
      "/k-home cityview/260323_TAN-HOA_BALCONY_FINAL_2-1.webp",
      "/k-home cityview/260328_TAN-HOA_V05_FINAL_2-1.webp",
      "/k-home cityview/260328_TAN-HOA_V06_FINAL_2-1.webp",
      "/k-home cityview/thiet-ke-can-ho-layout-khome-city-view-2048x764.jpg",
    ],
    amenities: ["Hồ bơi người lớn & trẻ em", "Sân chơi trẻ em", "Khu thể dục ngoài trời", "Nhà sinh hoạt cộng đồng", "Shophouse thương mại nội khu", "Hệ thống an ninh 24/7"],
    unitTypes: [
      { slug: "1pn-a", name: "Căn 1 Phòng Ngủ + A", bedrooms: 1, bathrooms: 1, constructionArea: "47,3m²", usableArea: "42,3m²", price: "950 triệu – 1,05 tỷ/căn", priceNumber: 950,  furnished: true,
        description: "**Căn hộ 1 Phòng Ngủ + A** là lựa chọn lý tưởng cho cặp vợ chồng trẻ hoặc cá nhân muốn sở hữu không gian riêng tư tại K-Home CityView với mức giá tốt nhất trong rổ hàng.\n\n**Diện tích & Bố cục**\n\nVới diện tích xây dựng **47,3m²** và diện tích sử dụng thực tế **42,3m²**, căn hộ được thiết kế tối ưu từng m² theo tiêu chuẩn Singapore. Không gian được phân chia hợp lý gồm: **1 phòng ngủ** rộng rãi, **1 nhà vệ sinh** đầy đủ tiện nghi, phòng khách mở thông thoáng, bếp hiện đại và ban công đón ánh sáng tự nhiên.\n\n**Nội thất bàn giao**\n\nCăn hộ được bàn giao **full nội thất** cao cấp theo tiêu chuẩn dự án, bao gồm toàn bộ nội thất cơ bản như tủ bếp, kệ bếp, tủ âm tường, sàn gỗ và hệ thống chiếu sáng — chỉ trừ các thiết bị điện tử. Cư dân chỉ cần mang theo đồ dùng cá nhân là có thể dọn vào ở ngay.\n\n**Giá bán & Chính sách**\n\nMức giá **950 triệu – 1,05 tỷ/căn** là mức giá nhà ở xã hội được Nhà nước phê duyệt, người mua được hưởng **lãi suất vay ưu đãi NOXH** từ các ngân hàng quốc doanh. Đây là cơ hội hiếm có để sở hữu nhà ở pháp lý rõ ràng tại khu vực trung tâm Biên Hòa.",
        images: [
          "/k-home cityview/Can-1PN-A/1pn-noxh-k-home-city-view.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-1.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-2.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-3.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-4-2048x1209.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-5.jpg",
          "/k-home cityview/Can-1PN-A/khome-cityview-nha-mau-can-ho-1PN-7.jpg",
        ]},
      { slug: "1pn-b", name: "Căn 1 Phòng Ngủ + B", bedrooms: 1, bathrooms: 2, constructionArea: "62,4m²", usableArea: "55,1m²", price: "1,25 tỷ – 1,40 tỷ/căn", priceNumber: 1250, furnished: true,
        description: "**Căn hộ 1 Phòng Ngủ + B** là phiên bản nâng cấp so với loại A, sở hữu diện tích rộng hơn và **2 nhà vệ sinh** riêng biệt — đáp ứng nhu cầu của các gia đình nhỏ hoặc cặp đôi cần không gian sinh hoạt thoải mái hơn.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **62,4m²** và diện tích sử dụng **55,1m²** cho phép bố trí không gian rộng rãi hơn: **1 phòng ngủ** master rộng, **2 nhà vệ sinh** (1 trong phòng ngủ, 1 cho khách), phòng khách – bếp mở thông thoáng và ban công rộng.\n\n**Nội thất bàn giao**\n\nCăn hộ bàn giao **full nội thất** theo tiêu chuẩn dự án, đảm bảo cư dân có thể sử dụng ngay mà không cần đầu tư thêm nhiều. Các thiết bị điện tử không nằm trong gói bàn giao.\n\n**Giá bán & Chính sách**\n\nMức giá **1,25 tỷ – 1,40 tỷ/căn** thuộc phân khúc nhà ở xã hội được Nhà nước kiểm soát, người mua được hưởng đầy đủ chính sách hỗ trợ vay vốn ưu đãi NOXH với lãi suất thấp hơn lãi suất thị trường.",
        images: [
          "/k-home cityview/Can-1PN-B/2pns-noxh-k-home-city-view-2048x1536.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-1.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-2.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-3.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-4-2048x1209.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-5.jpg",
          "/k-home cityview/Can-1PN-B/khome-cityview-nha-mau-can-ho-1PN-7.jpg",
        ]},
      { slug: "2pn", name: "Căn 2 Phòng Ngủ", bedrooms: 2, bathrooms: 2, constructionArea: "70,4m²", usableArea: "63,2m²", price: "1,50 tỷ – 1,60 tỷ/căn", priceNumber: 1500, furnished: true,
        description: "**Căn hộ 2 Phòng Ngủ** là lựa chọn phổ biến nhất tại K-Home CityView, phù hợp cho gia đình 3–4 thành viên với nhu cầu có phòng ngủ riêng cho con cái và không gian sinh hoạt chung thoải mái.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **70,4m²** và diện tích sử dụng **63,2m²** — đây là diện tích lý tưởng cho gia đình nhỏ. Bố cục gồm **2 phòng ngủ** đầy đủ cửa sổ đón sáng, **2 nhà vệ sinh** riêng biệt, phòng khách – bếp rộng và ban công thông thoáng.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện cao cấp theo tiêu chuẩn dự án. Toàn bộ các phòng đều được trang bị nội thất cố định chất lượng, sẵn sàng để ở ngay sau khi nhận bàn giao — ngoại trừ thiết bị điện tử.\n\n**Giá bán & Chính sách**\n\nMức giá **1,50 tỷ – 1,60 tỷ/căn** là mức giá NOXH cạnh tranh nhất thị trường Biên Hòa cho căn 2 phòng ngủ. Người đủ điều kiện mua NOXH được hưởng lãi suất vay ưu đãi từ **Ngân hàng Vietinbank, BIDV, Vietcombank, Agribank** theo chính sách nhà ở xã hội quốc gia.",
        images: [
          "/k-home cityview/Can-2PN/2pn-noxh-k-home-city-view-2048x1536.jpg",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-1.jpg",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-2.jpg",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-3.jpg.webp",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-4.jpg",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-6.jpg",
          "/k-home cityview/Can-2PN/khome-cityview-nha-mau-can-ho-2PN-8.jpg",
        ]},
      { slug: "3pn", name: "Căn hộ 3 phòng ngủ", bedrooms: 3, bathrooms: 2, constructionArea: "84,4m²", usableArea: "75,4m²", price: "1,80 tỷ – 2,00 tỷ/căn", priceNumber: 1800, furnished: true,
        description: "**Căn hộ 3 Phòng Ngủ** là loại căn lớn nhất và cao cấp nhất trong rổ hàng K-Home CityView, dành cho gia đình nhiều thế hệ hoặc gia đình có từ 2 con trở lên cần không gian sống rộng rãi, riêng tư và đầy đủ tiện nghi.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **84,4m²** và diện tích sử dụng **75,4m²** — là diện tích lớn nhất trong dự án. Bố cục tối ưu với **3 phòng ngủ** đầy đủ (1 phòng ngủ master + 2 phòng ngủ phụ), **2 nhà vệ sinh** tiện nghi, phòng khách – bếp rộng mở, ban công lớn và khu vực lưu trữ thông minh.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện với chất lượng đồng bộ theo tiêu chuẩn cao cấp của dự án. Đặc biệt, căn 3PN có phòng ngủ master với hệ thống tủ âm tường toàn bộ, nhà vệ sinh master riêng biệt hoàn toàn, và phòng khách có đủ diện tích để bố trí khu ăn uống gia đình.\n\n**Giá bán & Chính sách**\n\nMức giá **1,80 tỷ – 2,00 tỷ/căn** là mức giá nhà ở xã hội được Nhà nước phê duyệt và kiểm soát chặt chẽ. Đây là cơ hội hiếm có để sở hữu căn hộ 3 phòng ngủ pháp lý đầy đủ với mức giá thấp hơn nhiều so với thị trường thương mại.",
        images: [
          "/k-home cityview/Can-3PN/3pn-noxh-k-home-city-view.jpg",
          "/k-home cityview/Can-3PN/z8043585440423_c4eeb73748a69f41c37d6bd9786582eb.jpg",
          "/k-home cityview/Can-3PN/z8043585442660_e37f1a0db75375dac4ed416b73ece7e8.jpg",
          "/k-home cityview/Can-3PN/z8043585455366_2dda820049421cbd45648d9d5ac9f3d8.jpg",
          "/k-home cityview/Can-3PN/z8043585482160_d5b849ce2ee46420548001a9e3a59892.jpg",
          "/k-home cityview/Can-3PN/z8043585489809_81937cf59023f875a66f1cb8ee71e996.jpg",
          "/k-home cityview/Can-3PN/z8043585499389_46f12736b66e663d1b327ee7e381d01c.jpg",
        ]},
    ],
    status: "Đang bốc thăm", rating: 4.8, floorCount: 22, developer: "Kim Oanh Land • K-Home Group",
  },
  {
    id: "2", slug: "k-home-midtown-trang-bom", title: "K-Home Midtown Trảng Bom",
    location: "Giữa 4 tuyến đường 30/4 – Hùng Vương – Lý Nam Đế – Lê Đại Hành, P. Trảng Bom, Đồng Nai",
    type: "Căn hộ nhà ở xã hội", price: "Từ 750 Triệu", priceNumber: 0.75, area: "36,1m² - 68,8m²",
    image: "/k-home midtown/Du-an-K-Home-Midtown-3d-birdview-toan-canh-dem-2048x1150.webp",
    description: "Tọa lạc tại trung tâm huyện Trảng Bom, K-Home Midtown là dự án NOXH quy mô 13,97 hecta với 542 căn hộ và 20 căn shophouse, kết nối thuận tiện 4 tuyến đường lớn.",
    longDescription: "**Tổng quan dự án K-Home Midtown Trảng Bom**\n\n**K-Home Midtown** là dự án nhà ở xã hội (NOXH) phân khúc chất lượng cao do **Kim Oanh Land & K-Home Group** phát triển, tọa lạc ngay tại **trung tâm huyện Trảng Bom, Tỉnh Đồng Nai** — một trong những khu vực công nghiệp phát triển năng động bậc nhất vùng Đông Nam Bộ. Được quy hoạch trên quỹ đất rộng **13,97 ha**, đây là dự án có quy mô lớn nhất trong hệ thống 3 dự án K-Home tại Đồng Nai, kiến tạo không gian sống hiện đại và là giải pháp an cư bền vững cho hàng ngàn công nhân, người lao động và gia đình trẻ.\n\nDự án gồm **542 căn hộ NOXH** cao 15 tầng kết hợp cùng hệ thống **20 căn shophouse** thương mại sầm uất tại tầng đế, đáp ứng đa dạng nhu cầu từ an cư ổn định đến kinh doanh, mua sắm tiện lợi ngay trong nội khu.\n\n**Vị trí chiến lược – Kết nối vùng vượt trội**\n\nĐiểm nhấn tạo nên sức hút đặc biệt của K-Home Midtown chính là **vị trí tứ giác vàng** ngay trung tâm thị trấn Trảng Bom — giao điểm của **4 tuyến đường huyết mạch**: đường 30/4, đường Hùng Vương, đường Lý Nam Đế và đường Lê Đại Hành. Cấu trúc giao thông đa chiều này giúp cư dân kết nối nhanh chóng đến các khu công nghiệp lớn trong vùng như KCN Bàu Xéo, KCN Hố Nai, đồng thời dễ dàng di chuyển về trung tâm TP. Biên Hòa và TP. Hồ Chí Minh qua cao tốc TP.HCM – Long Thành – Dầu Giây.\n\n**Kiến trúc Singapore và đội ngũ đối tác uy tín**\n\nK-Home Midtown được thiết kế và quy hoạch theo **tiêu chuẩn Singapore** hiện đại, mang đến diện mạo kiến trúc tinh tế, hài hòa với thiên nhiên và tối ưu công năng sử dụng. Sự chỉn chu trong thiết kế được bảo chứng bởi các đối tác danh tiếng gồm **Global Vireon Studio**, **Kiến Trúc Việt**, **NAGECCO** và **K-City**.\n\n**Hệ sinh thái tiện ích nội khu toàn diện**\n\nVới quy mô quỹ đất rộng 13,97 ha, K-Home Midtown được đầu tư mạnh mẽ vào hệ thống tiện ích nội khu khép kín bậc nhất phân khúc NOXH. Ngay trong lòng dự án, cư dân được tận hưởng **hồ bơi hiện đại**, **khu vui chơi trẻ em** an toàn sáng tạo, **Sky Garden & vườn cảnh quan** rộng lớn – không gian xanh thư giãn lý tưởng giữa lòng khu đô thị công nghiệp.\n\nBên cạnh đó, **khu thể dục thể thao ngoài trời** và **nhà sinh hoạt cộng đồng** đa năng được bố trí hợp lý nhằm đáp ứng nhu cầu rèn luyện sức khỏe và giao lưu cộng đồng của toàn thể cư dân mọi lứa tuổi.",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1384.902626805889!2d107.00522593899112!3d10.956108940275927!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174e700442d0327%3A0xc12a0db1c85bf214!2sK-Home%20Midtown!5e0!3m2!1sen!2s!4v1784803611439!5m2!1sen!2s",
    gallery: [
      "/k-home midtown/Du-an-K-Home-Midtown-3d-birdview-toan-canh-dem-2048x1150.webp",
      "/k-home midtown/Du-an-K-Home-Midtown-3d-ho-boi-view-2-2048x1150.webp",
      "/k-home midtown/Du-an-K-Home-Midtown-3d-cong-vien-thap-tang-2048x1150.webp",
      "/k-home midtown/midtown.jpg",
      "/k-home midtown/midtown1.webp",
      "/k-home midtown/midtown2.webp",
      "/k-home midtown/midtown3.webp",
      "/k-home midtown/o34-384785.jpg",
      "/k-home midtown/k-home-midtown-mat-bang-can-ho-tang-dien-hinh.jpg.webp",
    ],
    amenities: ["Hồ bơi người lớn & trẻ em", "Sân chơi trẻ em", "Khu thể dục ngoài trời", "Sky Garden & vườn cảnh quan", "Shophouse thương mại nội khu", "Hệ thống an ninh 24/7"],
    unitTypes: [
      { slug: "studio",  name: "Căn Studio",  bedrooms: 0, bathrooms: 1, constructionArea: "36,1m²", usableArea: "32,0m²", price: "Từ 750 triệu/căn", priceNumber: 750,  furnished: true,
        description: "**Căn Studio K-Home Midtown** là loại căn compact thông minh với mức giá khởi điểm thấp nhất trong rổ hàng, phù hợp cho người độc thân, công nhân viên chức hoặc cặp đôi trẻ mới kết hôn muốn có chỗ ở riêng tư ngay trung tâm Trảng Bom.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **36,1m²** và diện tích sử dụng **32,0m²** — thiết kế studio mở thông minh, không phân chia vách cứng giữa phòng ngủ và phòng khách giúp không gian trông rộng rãi hơn thực tế. Bố cục bao gồm khu vực sinh hoạt kết hợp ngủ nghỉ, **1 nhà vệ sinh** đầy đủ tiện nghi, bếp nhỏ tiện lợi và ban công nhỏ đón gió.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện theo tiêu chuẩn dự án — toàn bộ nội thất cố định được thiết kế tích hợp tối ưu không gian: giường ngủ âm tường, tủ quần áo built-in, bàn làm việc gấp gọn và bếp compact. Chỉ trừ các thiết bị điện tử.\n\n**Giá bán & Chính sách**\n\nMức giá khởi điểm **750 triệu/căn** — đây là mức giá NOXH thấp nhất trong hệ thống K-Home, người đủ điều kiện được hưởng lãi suất vay ưu đãi NOXH, trả góp chỉ từ khoảng **3,5 triệu/tháng**.",
        images: [
        "/k-home midtown/Can-Studio/k-home-midtown-studio-1.jpg",
        "/k-home midtown/Can-Studio/01_XU.jpg",
        "/k-home midtown/Can-Studio/dsc01072.webp",
        "/k-home midtown/Can-Studio/dsc01084.webp",
        "/k-home midtown/Can-Studio/dsc01089.webp",
        "/k-home midtown/Can-Studio/dsc01093.webp",
        "/k-home midtown/Can-Studio/dsc01099.webp",
        "/k-home midtown/Can-Studio/dsc01105.webp",
        "/k-home midtown/Can-Studio/dsc01117.webp",
        "/k-home midtown/Can-Studio/dsc01125.webp",
        "/k-home midtown/Can-Studio/dsc01129.webp",
        "/k-home midtown/Can-Studio/dsc01134.webp",
      ]},
      { slug: "1pn-a",   name: "Căn 1 Phòng Ngủ + A", bedrooms: 1, bathrooms: 1, constructionArea: "47,0m²", usableArea: "42,0m²", price: "Từ 990 triệu/căn", priceNumber: 990,  furnished: true,
        description: "**Căn 1 Phòng Ngủ + A K-Home Midtown** là loại căn phổ biến nhất trong dự án, cân bằng hoàn hảo giữa diện tích sử dụng và mức giá — là lựa chọn hàng đầu cho các cặp đôi, gia đình nhỏ 2–3 người tại khu vực Trảng Bom.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **47,0m²** và diện tích sử dụng **42,0m²** với bố cục tách biệt rõ ràng: **1 phòng ngủ** riêng có cửa sổ đón sáng, **1 nhà vệ sinh** đầy đủ, phòng khách thông bếp rộng thoáng và ban công nhỏ. Cửa sổ lớn giúp không gian luôn sáng và thông gió tự nhiên.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện đồng bộ theo tiêu chuẩn dự án. Phòng ngủ có giường đôi, tủ âm tường; phòng khách có sofa, kệ TV; bếp có tủ bếp đầy đủ. Chỉ trừ các thiết bị điện tử.\n\n**Giá bán & Chính sách**\n\nGiá từ **990 triệu/căn** — vẫn thuộc khung NOXH, được hỗ trợ vay ưu đãi lãi suất thấp từ các ngân hàng quốc doanh. Mức trả góp hàng tháng phù hợp với thu nhập của công nhân và người lao động tại các KCN Trảng Bom.",
        images: [
        "/k-home midtown/Can-1PN-A/k-home-midtown-1PNA.jpg",
        "/k-home midtown/Can-1PN-A/02_CK.jpg",
        "/k-home midtown/Can-1PN-A/03_79.jpg",
        "/k-home midtown/Can-1PN-A/04.jpg",
      ]},
      { slug: "1pn-b",   name: "Căn 1 Phòng Ngủ + B", bedrooms: 1, bathrooms: 1, constructionArea: "55,1m²", usableArea: "48,8m²", price: "Từ 1,20 tỷ/căn",   priceNumber: 1200, furnished: true,
        description: "**Căn 1 Phòng Ngủ + B K-Home Midtown** là phiên bản mở rộng của loại 1PN+A, sở hữu diện tích lớn hơn đáng kể với không gian phòng khách và bếp thoải mái hơn — phù hợp cho gia đình trẻ cần thêm không gian sinh hoạt hoặc người có nhu cầu làm việc tại nhà.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **55,1m²** và diện tích sử dụng **48,8m²** — không gian phụ trội so với 1PN+A được phân bổ vào phòng khách rộng hơn, bếp tách biệt riêng và khu vực ăn uống có thể bố trí bàn 4–6 người. **1 phòng ngủ** đủ lớn cho giường đôi cỡ Queen, **1 nhà vệ sinh** và ban công.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện cao cấp, đồng bộ toàn bộ dự án. Không gian bếp được trang bị tủ bếp trên dưới đầy đủ. Chỉ trừ các thiết bị điện tử.\n\n**Giá bán & Chính sách**\n\nGiá từ **1,20 tỷ/căn** — mức giá NOXH được Nhà nước kiểm soát và phê duyệt, người mua đủ điều kiện được hưởng đầy đủ chính sách hỗ trợ tín dụng nhà ở xã hội với lãi suất ưu đãi.",
        images: [
        "/k-home midtown/Can-1PN-B/k-home-midtown-1PNB.jpg",
        "/k-home midtown/Can-1PN-B/02_CK.jpg",
        "/k-home midtown/Can-1PN-B/03_79.jpg",
        "/k-home midtown/Can-1PN-B/04.jpg",
      ]},
      { slug: "2pn",     name: "Căn 2 Phòng Ngủ",     bedrooms: 2, bathrooms: 2, constructionArea: "68,8m²", usableArea: "61,6m²", price: "Từ 1,50 tỷ/căn",   priceNumber: 1500, furnished: true,
        description: "**Căn 2 Phòng Ngủ K-Home Midtown** là loại căn cao cấp nhất trong rổ hàng NOXH của dự án, lý tưởng cho gia đình 3–4 người cần không gian sống đủ rộng, có phòng riêng cho con cái và không gian sinh hoạt chung thoải mái.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **68,8m²** và diện tích sử dụng **61,6m²** — bố cục 2 phòng ngủ riêng biệt với cửa sổ đón sáng tự nhiên, **2 nhà vệ sinh** riêng biệt (1 trong phòng ngủ master, 1 cho khách), phòng khách rộng thoáng và bếp có không gian bố trí bàn ăn gia đình đầy đủ. Ban công rộng có thể dùng làm góc thư giãn ngoài trời.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện cao cấp, đồng bộ toàn bộ dự án. Đặc biệt phòng khách của căn 2PN được thiết kế với diện tích đủ để bố trí sofa gia đình và khu vực ăn uống riêng. Chỉ trừ các thiết bị điện tử.\n\n**Giá bán & Chính sách**\n\nGiá từ **1,50 tỷ/căn** — là mức giá NOXH cạnh tranh nhất cho căn hộ 2 phòng ngủ tại khu vực Trảng Bom. Cư dân đủ điều kiện được hưởng lãi suất vay ưu đãi NOXH từ các ngân hàng quốc doanh với kỳ hạn vay dài.",
        images: [
        "/k-home midtown/Can-2PN/k-home-midtown-2pn.jpg",
        "/k-home midtown/Can-2PN/2pn liv.jpg",
        "/k-home midtown/Can-2PN/2pn-kit_Fy.jpg",
        "/k-home midtown/Can-2PN/2pn kid.jpg",
        "/k-home midtown/Can-2PN/dsc01317.webp",
        "/k-home midtown/Can-2PN/dsc01338.webp",
        "/k-home midtown/Can-2PN/dsc01350.webp",
        "/k-home midtown/Can-2PN/dsc01360.webp",
        "/k-home midtown/Can-2PN/dsc01367.webp",
        "/k-home midtown/Can-2PN/dsc01377.webp",
        "/k-home midtown/Can-2PN/dsc01385.webp",
        "/k-home midtown/Can-2PN/dsc01394.webp",
        "/k-home midtown/Can-2PN/dsc01397.webp",
        "/k-home midtown/Can-2PN/dsc01400.webp",
        "/k-home midtown/Can-2PN/dsc01401.webp",
        "/k-home midtown/Can-2PN/dsc01417.webp",
        "/k-home midtown/Can-2PN/dsc01426.webp",
        "/k-home midtown/Can-2PN/dsc01440.webp",
      ]},
    ],
    status: "Đã công bố", rating: 4.7, floorCount: 15, developer: "Kim Oanh Land • K-Home Group",
  },
  {
    id: "3", slug: "k-home-avenue-nhon-trach", title: "K-Home Avenue Nhơn Trạch",
    location: "Đường Nguyễn Ái Quốc (25C), Xã Nhơn Trạch, Tỉnh Đồng Nai",
    type: "Căn hộ nhà ở xã hội", price: "Từ 750 Triệu", priceNumber: 0.75, area: "37,7m² - 69,5m²",
    image: "/k-home avenue/Pc09-Loi-vao-shophouse_2-min.jpg.webp",
    description: "Tọa lạc trên trục đường Nguyễn Ái Quốc (25C), K-Home Avenue là dự án NOXH quy mô 5,3 hecta với 1.022 căn hộ và 82 căn shophouse, hưởng lợi trực tiếp từ hạ tầng sân bay Long Thành.",
    longDescription: "**Tổng quan dự án K-Home Avenue Nhơn Trạch**\n\n**K-Home Avenue** là dự án nhà ở xã hội (NOXH) chất lượng cao do **Kim Oanh Land & K-Home Group** phát triển, tọa lạc tại **đường Nguyễn Ái Quốc (Tỉnh lộ 25C), xã Nhơn Trạch, Tỉnh Đồng Nai** — khu vực đang được xác định là **cực tăng trưởng kinh tế trọng điểm** của vùng Đông Nam Bộ trong thập kỷ tới. Trên quỹ đất **5,3 ha**, dự án cung ứng **1.022 căn hộ NOXH** cùng **82 căn shophouse** thương mại, kiến tạo môi trường sống văn minh và hiện đại cho người lao động và các gia đình trẻ tại vùng ven sân bay quốc tế Long Thành.\n\n**Vị trí đón đầu hạ tầng – Sân bay Long Thành và cao tốc**\n\nK-Home Avenue được định vị ngay trên **trục Tỉnh lộ 25C** — tuyến đường kết nối trực tiếp từ Nhơn Trạch đến Cảng Hàng không Quốc tế Long Thành, công trình hạ tầng thế kỷ đang được khẩn trương xây dựng. Cư dân K-Home Avenue hưởng lợi kép: vừa nằm trong vùng tăng trưởng mạnh nhất Đồng Nai, vừa kết nối thuận lợi với **TP. Hồ Chí Minh**, **Biên Hòa** và các khu công nghiệp Nhơn Trạch qua hệ thống cao tốc và đường vành đai liên vùng đang được đầu tư đồng bộ.\n\n**Thiết kế quốc tế – Chuẩn sống Singapore**\n\nK-Home Avenue được quy hoạch và thiết kế bởi tập hợp các đơn vị tư vấn quốc tế đẳng cấp, dẫn đầu là **Surbana Jurong** — tập đoàn tư vấn quy hoạch đô thị Singapore với hơn 70 năm kinh nghiệm. Cùng với **Global Vireon Studio**, **Handong**, **Coninco** và **K-City**, K-Home Avenue mang đến ngôn ngữ kiến trúc tươi sáng, không gian sống tối ưu ánh sáng tự nhiên và thông gió, đạt tiêu chuẩn **công trình xanh** với chi phí vận hành tiết kiệm.\n\n**Hệ sinh thái tiện ích nội khu đẳng cấp**\n\nDù là dự án nhà ở xã hội, K-Home Avenue được đầu tư hệ thống tiện ích nội khu xứng tầm khu đô thị cao cấp. Cư dân tận hưởng **bể bơi hiện đại**, **khu vui chơi trẻ em** đầy màu sắc, **Sky Garden & vườn cảnh quan** mát mẻ, **khu nghỉ ngơi ngoài trời** thoáng đãng và **trạm sạc xe điện** tiên tiến đáp ứng xu hướng giao thông xanh.\n\nĐặc biệt, hệ thống **82 căn shophouse** khối đế tạo nên một **phố thương mại nội khu** sôi động, đáp ứng mọi nhu cầu mua sắm, ẩm thực và dịch vụ hàng ngày của cư dân ngay tại chân tòa nhà, không cần di chuyển ra ngoài.",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3920.298520835324!2d106.89406377488157!3d10.711442389433383!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31751946f2629b55%3A0x3fffa92e2b45f1d8!2sK-Home%20Avenue%20-%20Kim%20Oanh%20Homes!5e0!3m2!1sen!2s!4v1784803690040!5m2!1sen!2s",
    gallery: [
      "/k-home avenue/Pc09-Loi-vao-shophouse_2-min.jpg.webp",
      "/k-home avenue/PC01-TT-copy_2_2-min.jpg.webp",
      "/k-home avenue/PC02-TT-10K_2-min.jpg.webp",
      "/k-home avenue/PC03-TT-10K_2-min.jpg.webp",
      "/k-home avenue/Pc04-Tien-ich-tram-sac_2-min.jpg.webp",
      "/k-home avenue/Pc05-Tien-ich-khu-vui-choi_2-min.jpg.webp",
      "/k-home avenue/Pc06-Tien-ich-dung-nghi_2-min.jpg.webp",
      "/k-home avenue/Pc07-Tien-ich-be-boi_2-min.jpg.webp",
      "/k-home avenue/Pc08-Tien-ich-cong-vien_2-min.jpg.webp",
      "/k-home avenue/layout-can-ho-khome-avenue-nhon-trach.jpg",
    ],
    amenities: ["Hồ bơi người lớn & trẻ em", "Sân chơi trẻ em", "Khu thể dục ngoài trời", "Sky Garden & vườn cảnh quan", "82 căn shophouse thương mại", "Hệ thống an ninh 24/7"],
    unitTypes: [
      { slug: "studio",   name: "Căn Studio",    bedrooms: 0, bathrooms: 1, constructionArea: "37,7m²", usableArea: "33,3m²", price: "Từ 750 triệu/căn",       priceNumber: 750,  furnished: true,
        description: "**Căn Studio K-Home Avenue** là lựa chọn tối ưu cho người độc thân, công nhân kỹ thuật cao và cặp đôi trẻ tại khu vực Nhơn Trạch — nơi đang được đầu tư hạ tầng mạnh mẽ nhờ sân bay Long Thành. Đây là loại căn có mức giá khởi điểm thấp nhất và tỷ lệ đặt cọc cao nhất trong dự án.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **37,7m²** và diện tích sử dụng **33,3m²** — thiết kế studio linh hoạt tối ưu từng cm². Không gian mở thông thoáng với khu sinh hoạt kết hợp ngủ nghỉ, **1 nhà vệ sinh** đầy đủ tiện nghi, bếp mini hiện đại và ban công nhỏ đón gió mát.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** cao cấp theo tiêu chuẩn Singapore của dự án. Nội thất được thiết kế đa năng, tiết kiệm tối đa không gian: giường ngủ tích hợp tủ, bàn làm việc gấp gọn, tủ bếp compact và khu vệ sinh clean-line hiện đại. Chỉ trừ các thiết bị điện tử.\n\n**Giá bán & Tiềm năng**\n\nGiá từ **750 triệu/căn** — mức giá NOXH thấp nhất trong hệ thống K-Home, được hỗ trợ lãi suất vay ưu đãi. Khu vực Nhơn Trạch đang trong giai đoạn tăng trưởng mạnh nhờ hạ tầng sân bay Long Thành, căn studio tại đây có tiềm năng cho thuê rất tốt.",
        images: [
        "/k-home avenue/Can-Studio/layout-can-ho-khome-avenue-studio.jpg",
        "/k-home avenue/Can-Studio/01_XU.jpg",
        "/k-home avenue/Can-Studio/dsc01072.webp",
        "/k-home avenue/Can-Studio/dsc01084.webp",
        "/k-home avenue/Can-Studio/dsc01089.webp",
        "/k-home avenue/Can-Studio/dsc01093.webp",
        "/k-home avenue/Can-Studio/dsc01099.webp",
        "/k-home avenue/Can-Studio/dsc01105.webp",
        "/k-home avenue/Can-Studio/dsc01117.webp",
        "/k-home avenue/Can-Studio/dsc01125.webp",
        "/k-home avenue/Can-Studio/dsc01129.webp",
        "/k-home avenue/Can-Studio/dsc01134.webp",
      ]},
      { slug: "1pn",      name: "Căn 1 Phòng Ngủ +",      bedrooms: 1, bathrooms: 1, constructionArea: "46,6m²", usableArea: "41,6m²", price: "Từ 990 triệu/căn",       priceNumber: 990,  furnished: true,
        description: "**Căn 1 Phòng Ngủ+ K-Home Avenue** là loại căn phổ biến nhất trong dự án, cân bằng tốt giữa diện tích, công năng và giá cả — phù hợp cho cặp đôi trẻ và gia đình 2–3 người muốn sở hữu tổ ấm đầu tiên tại khu vực cửa ngõ sân bay Long Thành.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **46,6m²** và diện tích sử dụng **41,6m²** với bố cục tách biệt rõ ràng: **1 phòng ngủ** riêng biệt đón ánh sáng tự nhiên, **1 nhà vệ sinh** tiện nghi, phòng khách thông bếp mở rộng thoáng và ban công đón gió. Cửa sổ được thiết kế đón hướng Đông hoặc Tây Nam theo tiêu chuẩn thiết kế Singapore.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện theo tiêu chuẩn dự án được tư vấn bởi **Surbana Jurong** Singapore. Toàn bộ nội thất cố định được lắp đặt sẵn: tủ âm tường phòng ngủ, tủ bếp trên dưới, sàn gỗ, trần thạch cao và hệ thống chiếu sáng. Chỉ trừ thiết bị điện tử.\n\n**Giá bán & Tiềm năng**\n\nGiá từ **990 triệu/căn** — mức giá NOXH được Nhà nước phê duyệt, hỗ trợ vay lãi suất ưu đãi. Nhơn Trạch là khu vực có tốc độ tăng giá BĐS nhanh nhất vùng Đông Nam Bộ nhờ sân bay Long Thành — tiềm năng tăng giá và cho thuê rất cao trong tương lai gần.",
        images: [
        "/k-home avenue/Can-1PN/layout-can-ho-khome-avenue-1PN.jpg",
        "/k-home avenue/Can-1PN/dsc01146.webp",
        "/k-home avenue/Can-1PN/dsc01150.webp",
        "/k-home avenue/Can-1PN/dsc01152.webp",
        "/k-home avenue/Can-1PN/dsc01162.webp",
        "/k-home avenue/Can-1PN/dsc01184.webp",
        "/k-home avenue/Can-1PN/dsc01190.webp",
        "/k-home avenue/Can-1PN/dsc01209.webp",
        "/k-home avenue/Can-1PN/dsc01220.webp",
        "/k-home avenue/Can-1PN/dsc01245.webp",
        "/k-home avenue/Can-1PN/dsc01269.webp",
        "/k-home avenue/Can-1PN/dsc01279.webp",
        "/k-home avenue/Can-1PN/dsc01286.webp",
      ]},
      { slug: "2pn-nho",  name: "Căn 2 Phòng Ngủ (Nhỏ)", bedrooms: 2, bathrooms: 2, constructionArea: "65,7m²", usableArea: "58,4m²", price: "1,23 tỷ – 1,39 tỷ/căn", priceNumber: 1230, furnished: true,
        description: "**Căn 2 Phòng Ngủ (Nhỏ) K-Home Avenue** là loại căn 2 phòng ngủ có diện tích vừa phải, tối ưu cho gia đình 3–4 người muốn có không gian riêng tư cho mỗi thành viên với mức ngân sách hợp lý nhất trong phân khúc 2PN của dự án.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **65,7m²** và diện tích sử dụng **58,4m²** — phân bổ hợp lý với **2 phòng ngủ** riêng biệt (phòng ngủ chính rộng đủ giường đôi Queen, phòng ngủ phụ đủ giường đơn hoặc bàn làm việc), **2 nhà vệ sinh** tiện nghi, phòng khách kết hợp bàn ăn và ban công thoáng.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện cao cấp, đồng bộ toàn dự án theo tiêu chuẩn thiết kế Singapore. Cả 2 phòng ngủ đều có tủ âm tường built-in, phòng khách đủ diện tích bố trí bàn ăn 4 người. Chỉ trừ thiết bị điện tử.\n\n**Giá bán & Tiềm năng**\n\nGiá từ **1,23 tỷ đến 1,39 tỷ/căn** tùy tầng và hướng nhìn — đây là mức giá NOXH được kiểm soát, thấp hơn đáng kể so với căn hộ thương mại cùng diện tích tại Nhơn Trạch. Tiềm năng cho thuê cao nhờ vị trí gần các KCN Nhơn Trạch và cửa ngõ sân bay Long Thành.",
        images: [
        "/k-home avenue/Can-2PN-nho/layout-can-ho-khome-avenue-2PNA.jpg",
        "/k-home avenue/Can-2PN-nho/dsc01317.webp",
        "/k-home avenue/Can-2PN-nho/dsc01338.webp",
        "/k-home avenue/Can-2PN-nho/dsc01350.webp",
        "/k-home avenue/Can-2PN-nho/dsc01360.webp",
        "/k-home avenue/Can-2PN-nho/dsc01367.webp",
        "/k-home avenue/Can-2PN-nho/dsc01377.webp",
        "/k-home avenue/Can-2PN-nho/dsc01385.webp",
        "/k-home avenue/Can-2PN-nho/dsc01394.webp",
        "/k-home avenue/Can-2PN-nho/dsc01397.webp",
        "/k-home avenue/Can-2PN-nho/dsc01400.webp",
        "/k-home avenue/Can-2PN-nho/dsc01401.webp",
        "/k-home avenue/Can-2PN-nho/dsc01417.webp",
        "/k-home avenue/Can-2PN-nho/dsc01426.webp",
        "/k-home avenue/Can-2PN-nho/dsc01440.webp",
      ]},
      { slug: "2pn-lon",  name: "Căn 2 Phòng Ngủ (Lớn)", bedrooms: 2, bathrooms: 2, constructionArea: "69,5m²", usableArea: "62,2m²", price: "1,40 tỷ – 1,47 tỷ/căn", priceNumber: 1400, furnished: true,
        description: "**Căn 2 Phòng Ngủ (Lớn) K-Home Avenue** là loại căn cao cấp nhất trong rổ hàng NOXH của dự án, dành cho gia đình cần không gian sinh hoạt rộng rãi hơn với diện tích phòng ngủ master lớn và phòng khách thoải mái hơn phiên bản nhỏ.\n\n**Diện tích & Bố cục**\n\nDiện tích xây dựng **69,5m²** và diện tích sử dụng **62,2m²** — diện tích vượt trội so với 2PN (Nhỏ) được phân bổ vào phòng ngủ master rộng hơn (đủ cho giường King size), phòng khách có diện tích bố trí bàn ăn 6 người và góc làm việc riêng. **2 nhà vệ sinh** với master bathroom riêng biệt hoàn toàn.\n\n**Nội thất bàn giao**\n\nBàn giao **full nội thất** hoàn thiện cao cấp nhất trong hệ thống K-Home Avenue, phòng ngủ master có tủ âm tường walk-in đặc biệt rộng rãi. Toàn bộ nội thất cố định được thiết kế đồng bộ theo tiêu chuẩn Singapore. Chỉ trừ thiết bị điện tử.\n\n**Giá bán & Tiềm năng**\n\nGiá từ **1,40 tỷ đến 1,47 tỷ/căn** — là mức giá đỉnh trong rổ hàng NOXH K-Home Avenue nhưng vẫn thấp hơn rất nhiều so với căn hộ thương mại cùng diện tích. Vị trí Nhơn Trạch đang trong giai đoạn bùng nổ hạ tầng, loại căn lớn nhất thường có khả năng tăng giá mạnh nhất trong dài hạn.",
        images: [
        "/k-home avenue/Can-2PN-lon/layout-can-ho-khome-avenue-2PNB.jpg",
        "/k-home avenue/Can-2PN-lon/dsc01317.webp",
        "/k-home avenue/Can-2PN-lon/dsc01338.webp",
        "/k-home avenue/Can-2PN-lon/dsc01350.webp",
        "/k-home avenue/Can-2PN-lon/dsc01360.webp",
        "/k-home avenue/Can-2PN-lon/dsc01367.webp",
        "/k-home avenue/Can-2PN-lon/dsc01377.webp",
        "/k-home avenue/Can-2PN-lon/dsc01385.webp",
        "/k-home avenue/Can-2PN-lon/dsc01394.webp",
        "/k-home avenue/Can-2PN-lon/dsc01397.webp",
        "/k-home avenue/Can-2PN-lon/dsc01400.webp",
        "/k-home avenue/Can-2PN-lon/dsc01401.webp",
        "/k-home avenue/Can-2PN-lon/dsc01417.webp",
        "/k-home avenue/Can-2PN-lon/dsc01426.webp",
        "/k-home avenue/Can-2PN-lon/dsc01440.webp",
      ]},
    ],
    status: "Sắp công bố", rating: 4.8, floorCount: 12, developer: "Kim Oanh Land • K-Home Group",
  },
];

export default function handler(_req: VercelRequest, res: VercelResponse) {
  res.setHeader("Cache-Control", "s-maxage=3600, stale-while-revalidate");
  return res.json(DATA);
}
