import type { VercelRequest, VercelResponse } from "@vercel/node";

// AUTO-GENERATED — run: node scripts/generate-api-functions.mjs
// Data inlined from src/data/staticProjects.ts — no external imports needed
const DATA = [
{
    id: "1",
    slug: "k-home-cityview-ho-nai",
    title: "K-Home CityView Biên Hòa",
    location: "Đường Điểu Xiển, Phường Hố Nai, TP. Biên Hòa, Đồng Nai",
    type: "Căn hộ nhà ở xã hội",
    price: "Từ 950 Triệu",
    priceNumber: 0.95,
    area: "47,3m² - 84,4m²",
    image: "/k-home cityview/V34_TAN-HOA_EXT_FACADE_FINAL_2.webp",
    description: "K-Home CityView Hố Nai – nhà ở xã hội chuẩn Singapore tại đường Điểu Xiển, Biên Hòa. 1.328 căn NOXH + 39 shophouse, diện tích 47–84m², thiết kế Surbana Jurong, tiêu chuẩn xanh EDGE, giá từ 950 triệu, lãi suất 5,4%/năm, bàn giao nội thất 2028, hỗ trợ hồ sơ miễn phí.",
    longDescription: "**Tổng quan dự án K-Home CityView Hố Nai**\n\n**K-Home CityView** là dự án nhà ở xã hội (NOXH) chuẩn Singapore do **Kim Oanh Land** – thành viên Tập đoàn Kim Oanh Group – phát triển, tọa lạc tại mặt tiền **đường Điểu Xiển**, phường Hố Nai, thành phố Biên Hòa, tỉnh Đồng Nai. Dự án được quy hoạch trên quỹ đất rộng **2,85 ha** với **4 tòa tháp cao 22 tầng**, cung cấp khoảng **1.328 căn hộ nhà ở xã hội** cùng hệ thống **39 căn shophouse** khối đế.",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.0500305663313!2d106.90024047509125!3d10.959593489200515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174ddbb3dca0a9d%3A0x6a42d2ebd1b96a45!2sK-Home%20Cityview%20-%20Kim%20Oanh%20Land!5e0!3m2!1sen!2s!4v1787364751941!5m2!1sen!2s",
    gallery: [
      "/k-home cityview/V34_TAN-HOA_EXT_FACADE_FINAL_2.webp",
      "/k-home cityview/V02_TAN-HOA_EXT_BBQ-GARDEN_FN_2-1.webp",
      "/k-home cityview/TAN-HOA_AERIAL_1_DRAFT-3_2-1.webp",
      "/k-home cityview/V03_TAN-HOA_EXT_NOXH_KID-PLAYGROUND_FINAL_2-1.webp",
      "/k-home cityview/V32_TAN-HOA_EXT_AERIAL_2_FINAL_2.webp",
      "/k-home cityview/V11_TH_EXT_NOTM_POOL_2.webp",
      "/k-home cityview/V12_TH_EXT_NOXH_POOL_2.webp",
      "/k-home cityview/V35_TAN-HOA_EXT_NOXH_POOL2_2.jpg",
      "/k-home cityview/V10_TH_EXT_GARDEN_FINAL_2.webp",
    ],
    galleryAlts: [
      "Phối cảnh tổng thể dự án nhà ở xã hội K-Home CityView Hố Nai Biên Hòa Đồng Nai",
      "Khu BBQ và vườn cộng đồng nội khu K-Home CityView Kim Oanh Land",
      "Toàn cảnh dự án NOXH K-Home CityView nhìn từ trên cao Hố Nai Biên Hòa",
    ],
    amenities: ["Hồ bơi người lớn & trẻ em", "Sân chơi trẻ em an toàn", "Khu thể dục ngoài trời", "Nhà sinh hoạt cộng đồng đa năng", "Vườn treo tầng 3", "Khu BBQ sinh hoạt gia đình", "Shophouse & minimart nội khu", "Nhà trẻ & trường học trong khuôn viên"],
    unitTypes: [
      { slug: "can-ho-1-phong-ngu-a", name: "Căn 1 Phòng Ngủ + A", bedrooms: 1, bathrooms: 1, constructionArea: "47,3m²", usableArea: "42,3m²", price: "950 triệu – 1,08 tỷ/căn", priceNumber: 950, furnished: true, description: "Căn 1PN+A tiêu chuẩn Singapore K-Home CityView", images: ["/k-home cityview/Can-1PN-A/1pn-noxh-k-home-city-view.jpg"] },
      { slug: "can-ho-1-phong-ngu-b", name: "Căn 1 Phòng Ngủ + B", bedrooms: 1, bathrooms: 2, constructionArea: "62,4m²", usableArea: "55,1m²", price: "1,20 tỷ – 1,40 tỷ/căn", priceNumber: 1200, furnished: true, description: "Căn 1PN+B tiêu chuẩn Singapore K-Home CityView", images: ["/k-home cityview/Can-1PN-B/2pns-noxh-k-home-city-view-2048x1536.jpg"] },
      { slug: "can-ho-2-phong-ngu-cityview", name: "Căn 2 Phòng Ngủ", bedrooms: 2, bathrooms: 2, constructionArea: "70,4m²", usableArea: "63,2m²", price: "1,50 tỷ – 1,70 tỷ/căn", priceNumber: 1500, furnished: true, description: "Căn 2PN tiêu chuẩn Singapore K-Home CityView", images: ["/k-home cityview/Can-2PN/2pn-noxh-k-home-city-view-2048x1536.jpg"] },
      { slug: "can-ho-3-phong-ngu", name: "Căn hộ 3 phòng ngủ", bedrooms: 3, bathrooms: 2, constructionArea: "84,4m²", usableArea: "75,4m²", price: "1,80 tỷ – 2,00 tỷ/căn", priceNumber: 1800, furnished: true, description: "Căn 3PN tiêu chuẩn Singapore K-Home CityView", images: ["/k-home cityview/Can-3PN/3pn-noxh-k-home-city-view.jpg"] },
    ],
    status: "Đang bốc thăm",
    rating: 4.8,
    floorCount: 22,
    developer: "Kim Oanh Land (Tập đoàn Kim Oanh Group)",
  },
  {
    id: "2",
    slug: "k-home-midtown-trang-bom",
    title: "K-Home Midtown Trảng Bom",
    location: "Giữa 4 tuyến đường 30/4 – Hùng Vương – Lý Nam Đế – Lê Đại Hành, P. Trảng Bom, Đồng Nai",
    type: "Căn hộ nhà ở xã hội",
    price: "Từ 750 Triệu",
    priceNumber: 0.75,
    area: "36,1m² - 68,8m²",
    image: "/k-home midtown/Du-an-K-Home-Midtown-3d-birdview-toan-canh-dem-2048x1150.webp",
    description: "K-Home Midtown Trảng Bom – dự án nhà ở xã hội quy mô 13,97 ha, 542 căn hộ. Vị trí trung tâm Trảng Bom, giao 4 tuyến đường lớn.",
    longDescription: "**Tổng quan dự án K-Home Midtown Trảng Bom**",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.0666616089666!2d107.0031419750912!3d10.958337189201718!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174e7e5c698818b%3A0x3c5a8151d5490c00!2zTmjDoCDhu54gWMOjIEjhu5lpIFRy4bqjbmcgQm9tIC0gSy1Ib21lIE1pZHRvd24gLSBLT0c!5e0!3m2!1sen!2s!4v1789697867235!5m2!1sen!2s",
    gallery: [
      "/k-home midtown/Du-an-K-Home-Midtown-3d-birdview-toan-canh-dem-2048x1150.webp",
      "/k-home midtown/Du-an-K-Home-Midtown-3d-ho-boi-view-2-2048x1150.webp",
      "/k-home midtown/Du-an-K-Home-Midtown-3d-cong-vien-thap-tang-2048x1150.webp",
      "/k-home midtown/midtown.jpg",
      "/k-home midtown/midtown1.webp",
      "/k-home midtown/midtown2.webp",
      "/k-home midtown/midtown3.webp",
      "/k-home midtown/o34-384785.jpg",
      "/slide-k-home-midtown/phoi-canh-tong-the-du-an-k-home-midtown-trang-bom-phong-cach-song-chuan-singapor.jpg",
      "/slide-k-home-midtown/ho-boi-ngoai-troi-tai-k-home-midtown-trang-bom-khong-gian-thu-gian-va-tien-ich-n.jpg",
      "/slide-k-home-midtown/khong-gian-song-tai-k-home-midtown-trang-bom-view-huong-cong-vien-va-tien-ich-no.jpg",
      "/slide-k-home-midtown/tien-ich-va-cong-trinh-xanh-edge-tai-k-home-midtown-giam-20-dien-nang-nuoc-va-kh.jpg",
      "/slide-k-home-midtown/10-diem-nhan-noi-bat-cua-du-an-nha-o-xa-hoi-k-home-midtown-trang-bom.jpg",
      "/k-home midtown/k-home-midtown-mat-bang-can-ho-tang-dien-hinh.jpg",
    ],
    galleryAlts: [
      "Phối cảnh toàn cảnh đêm dự án nhà ở xã hội K-Home Midtown Trảng Bom nhìn từ trên cao",
      "Phối cảnh hồ bơi ngoài trời tràn bờ chuẩn Singapore tại K-Home Midtown Trảng Bom",
      "Phối cảnh công viên nội khu và khu thể thao ngoài trời K-Home Midtown Trảng Bom",
      "Phối cảnh tổng thể tòa tháp căn hộ K-Home Midtown Trảng Bom Kim Oanh Land",
      "Phối cảnh góc phố sầm uất và kiến trúc hiện đại K-Home Midtown Trảng Bom",
      "Phối cảnh cảnh quan cây xanh và lối dạo bộ nội khu K-Home Midtown Trảng Bom",
      "Phối cảnh sảnh đón và khu shophouse thương mại tầng trệt K-Home Midtown",
      "Không gian sống thư giãn chuẩn Singapore tại dự án K-Home Midtown Trảng Bom",
      "Phong cách sống chuẩn Singapore với không gian xanh và tiện ích đầy đủ K-Home Midtown",
      "Hồ bơi ngoài trời và tiện ích nội khu chuẩn Singapore K-Home Midtown Trảng Bom",
      "Không gian sống view hướng công viên nội khu K-Home Midtown Trảng Bom",
      "Tiêu chuẩn công trình xanh EDGE tiết kiệm 20% điện nước tại K-Home Midtown Trảng Bom",
      "10 điểm nhấn nổi bật dự án nhà ở xã hội K-Home Midtown Trảng Bom Kim Oanh Land",
      "Mặt bằng tầng căn hộ điển hình dự án nhà ở xã hội K-Home Midtown Trảng Bom",
    ],
    amenities: ["Hồ bơi", "Sân chơi trẻ em", "Khu thể dục"],
    unitTypes: [
      { slug: "can-ho-studio", name: "Căn Studio", bedrooms: 0, bathrooms: 1, constructionArea: "36,1m²", usableArea: "32,0m²", price: "Từ 750 triệu/căn", priceNumber: 750, furnished: true, description: "Studio Midtown", images: ["/k-home midtown/Can-Studio/k-home-midtown-studio-1.jpg"] },
      { slug: "can-ho-1-phong-ngu-a", name: "Căn 1 Phòng Ngủ + A", bedrooms: 1, bathrooms: 1, constructionArea: "47,0m²", usableArea: "42,0m²", price: "Từ 990 triệu/căn", priceNumber: 990, furnished: true, description: "1PN+A Midtown", images: ["/k-home midtown/Can-1PN-A/k-home-midtown-1PNA.jpg"] },
      { slug: "can-ho-1-phong-ngu-b", name: "Căn 1 Phòng Ngủ + B", bedrooms: 1, bathrooms: 1, constructionArea: "55,1m²", usableArea: "48,8m²", price: "Từ 1,20 tỷ/căn", priceNumber: 1200, furnished: true, description: "1PN+B Midtown", images: ["/k-home midtown/Can-1PN-B/k-home-midtown-1PNB.jpg"] },
      { slug: "can-ho-2-phong-ngu", name: "Căn 2 Phòng Ngủ", bedrooms: 2, bathrooms: 2, constructionArea: "68,8m²", usableArea: "61,6m²", price: "Từ 1,50 tỷ/căn", priceNumber: 1500, furnished: true, description: "2PN Midtown", images: ["/k-home midtown/Can-2PN/k-home-midtown-2pn.jpg"] }
    ],
    status: "Đã công bố",
    rating: 4.7,
    floorCount: 15,
    developer: "Kim Oanh Land (Tập đoàn Kim Oanh Group)",
  },
  {
    id: "3",
    slug: "k-home-avenue-nhon-trach",
    title: "K-Home Avenue Nhơn Trạch",
    location: "Đường Nguyễn Ái Quốc (25C), Xã Nhơn Trạch, Tỉnh Đồng Nai",
    type: "Căn hộ nhà ở xã hội",
    price: "Từ 750 Triệu",
    priceNumber: 0.75,
    area: "37,7m² - 69,5m²",
    image: "/k-home avenue/Pc09-Loi-vao-shophouse_2-min.jpg.webp",
    description: "K-Home Avenue Nhơn Trạch – dự án nhà ở xã hội tại đường 25C, quy mô 5,3 ha, 1.022 căn hộ. Gần sân bay Long Thành.",
    longDescription: "**Tổng quan dự án K-Home Avenue Nhơn Trạch**",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3920.328778771721!2d106.89716427508769!3d10.709104289435636!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317523bdb83ec7b7%3A0x2844491869659151!2sK-Home%20Avenue%20-%20Kim%20Oanh%20Land!5e0!3m2!1sen!2s!4v1789027052579!5m2!1sen!2s",
    gallery: [
      "/k-home avenue/Pc09-Loi-vao-shophouse_2-min.jpg.webp",
      "/k-home avenue/PC01-TT-copy_2_2-min.jpg.webp",
      "/k-home avenue/Pc07-Tien-ich-be-boi_2-min.jpg.webp",
      "/k-home avenue/PC02-TT-10K_2-min.jpg.webp",
      "/k-home avenue/PC03-TT-10K_2-min.jpg.webp",
      "/k-home avenue/Pc08-Tien-ich-cong-vien_2-min.jpg.webp",
      "/k-home avenue/Pc05-Tien-ich-khu-vui-choi_2-min.jpg.webp",
      "/k-home avenue/Pc06-Tien-ich-dung-nghi_2-min.jpg.webp",
      "/k-home avenue/Pc04-Tien-ich-tram-sac_2-min.jpg.webp",
      "/slide-k-home-avenue/phoi-canh-tong-the-du-an-nha-o-xa-hoi-k-home-avenue-chuan-singapore-tai-nhon-tra.jpg",
      "/slide-k-home-avenue/he-tien-ich-da-lop-tai-k-home-avenue-ho-boi-san-choi-va-tien-ich-ngoai-khu-xung-.jpg",
      "/slide-k-home-avenue/tong-quan-du-an-k-home-avenue-nang-tam-chuan-song-xanh-voi-4-block-cao-12-tang-t.jpg",
      "/slide-k-home-avenue/10-gia-tri-cot-loi-cua-du-an-nha-o-xa-hoi-k-home-avenue.jpg",
      "/k-home avenue/layout-can-ho-khome-avenue-nhon-trach.jpg",
    ],
    galleryAlts: [
      "Phối cảnh lối vào shophouse thương mại dự án K-Home Avenue Nhơn Trạch",
      "Phối cảnh tổng thể các block tháp căn hộ K-Home Avenue Nhơn Trạch Đồng Nai",
      "Bể bơi nội khu phong cách resort chuẩn Singapore tại K-Home Avenue Nhơn Trạch",
      "Phối cảnh mặt tiền tháp căn hộ và cảnh quan nội khu K-Home Avenue",
      "Không gian sống xanh và lối dạo bộ thư giãn K-Home Avenue Nhơn Trạch",
      "Công viên cây xanh và khu sinh hoạt cộng đồng ngoài trời K-Home Avenue",
      "Khu vui chơi trẻ em an toàn và năng động tại K-Home Avenue Nhơn Trạch",
      "Chòi dừng nghỉ và vườn cảnh quan thư giãn nội khu K-Home Avenue Nhơn Trạch",
      "Tiện ích trạm sạc xe điện thông minh nội khu K-Home Avenue Nhơn Trạch",
      "Phối cảnh tổng thể dự án nhà ở xã hội K-Home Avenue chuẩn Singapore tại Nhơn Trạch",
      "Hệ tiện ích đa lớp tại K-Home Avenue hồ bơi sân chơi và tiện ích ngoại khu",
      "Tổng quan dự án K-Home Avenue nâng tầm chuẩn sống xanh với 4 block cao 12 tầng",
      "10 giá trị cốt lõi của dự án nhà ở xã hội K-Home Avenue Nhơn Trạch Kim Oanh Land",
      "Mặt bằng bố trí căn hộ tầng điển hình dự án K-Home Avenue Nhơn Trạch",
    ],
    amenities: ["Hồ bơi", "Sân chơi trẻ em"],
    unitTypes: [
      { slug: "can-ho-studio", name: "Căn Studio", bedrooms: 0, bathrooms: 1, constructionArea: "37,7m²", usableArea: "33,3m²", price: "Từ 750 triệu/căn", priceNumber: 750, furnished: true, description: "Studio Avenue", images: ["/k-home avenue/Can-Studio/layout-can-ho-khome-avenue-studio.jpg"] },
      { slug: "can-ho-1-phong-ngu", name: "Căn 1 Phòng Ngủ +", bedrooms: 1, bathrooms: 1, constructionArea: "46,6m²", usableArea: "41,6m²", price: "Từ 990 triệu/căn", priceNumber: 990, furnished: true, description: "1PN Avenue", images: ["/k-home avenue/Can-1PN/layout-can-ho-khome-avenue-1PN.jpg"] },
      { slug: "can-ho-2-phong-ngu", name: "Căn 2 Phòng Ngủ (Nhỏ)", bedrooms: 2, bathrooms: 2, constructionArea: "65,7m²", usableArea: "58,4m²", price: "1,23 tỷ – 1,39 tỷ/căn", priceNumber: 1230, furnished: true, description: "2PN Nhỏ Avenue", images: ["/k-home avenue/Can-2PN-nho/layout-can-ho-khome-avenue-2PNA.jpg"] },
      { slug: "can-ho-2-phong-ngu-b-avenue", name: "Căn 2 Phòng Ngủ (Lớn)", bedrooms: 2, bathrooms: 2, constructionArea: "69,5m²", usableArea: "62,2m²", price: "1,40 tỷ – 1,47 tỷ/căn", priceNumber: 1400, furnished: true, description: "2PN Lớn Avenue", images: ["/k-home avenue/Can-2PN-lon/layout-can-ho-khome-avenue-2PNB.jpg"] }
    ],
    status: "Đang bốc thăm",
    rating: 4.8,
    floorCount: 12,
    developer: "Kim Oanh Land (Tập đoàn Kim Oanh Group)",
  },
  {
    id: "4",
    slug: "k-home-skyview-trang-bom",
    title: "K-Home SkyView Trảng Bom",
    location: "Khu đô thị Bàu Xéo, Quốc Lộ 1A, TT. Trảng Bom, Tỉnh Đồng Nai",
    type: "Căn hộ nhà ở xã hội",
    status: "Sắp mở bán",
    price: "Từ 750 Triệu",
    priceNumber: 0.75,
    area: "37,0m² - 68,0m²",
    image: "https://res.cloudinary.com/dthv0nsq/image/upload/v1789373120/k-home-skyview/noxh-skyview02.jpg",
    description: "K-Home SkyView Bàu Xéo Trảng Bom – dự án nhà ở xã hội chuẩn Singapore tại KĐT Bàu Xéo. Giá từ 750 triệu, vay gói 5,4%/năm, thiết kế Surbana Jurong, bàn giao full nội thất.",
    longDescription: "**Tổng quan dự án K-Home SkyView Bàu Xéo Trảng Bom**\n\n**K-Home SkyView** (K-Home Sky View) là dự án nhà ở xã hội chuẩn Singapore do **Kim Oanh Land** (Tập đoàn Kim Oanh Group) phát triển tại **Khu đô thị Bàu Xéo**, thị trấn Trảng Bom, tỉnh Đồng Nai. Dự án quy hoạch trên khu đất hơn **1,08 ha** gồm các tòa tháp cao 9 – 12 tầng, cung cấp gần **600 căn hộ NOXH** chất lượng cao.",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.541172084478!2d107.0185!3d10.9655!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTDCsDU3JzU1LjgiTiAxMDfCsDAxJzA2LjYiRQ!5e0!3m2!1svi!2svn!4v1789373500000!5m2!1svi!2svn",
    gallery: [
      "https://res.cloudinary.com/dthv0nsq/image/upload/v1789373120/k-home-skyview/noxh-skyview02.jpg",
      "https://res.cloudinary.com/dthv0nsq/image/upload/q_auto,f_auto/k-home-skyview/noxh-skyview01",
      "https://res.cloudinary.com/dthv0nsq/image/upload/q_auto,f_auto/k-home-skyview/noxh-skyview03",
    ],
    galleryAlts: [
      "Phối cảnh tổng thể dự án nhà ở xã hội K-Home SkyView Bàu Xéo Trảng Bom",
      "Góc nhìn cận cảnh tháp căn hộ K-Home SkyView Kim Oanh Land",
      "Phối cảnh ban đêm dự án K-Home SkyView Bàu Xéo Đồng Nai",
      "Phối cảnh tổng thể trên cao K-Home SkyView Trảng Bom",
    ],
    amenities: ["Hồ bơi người lớn & trẻ em", "Sân chơi trẻ em an toàn", "Khu thể dục ngoài trời", "Công viên cảnh quan & lối dạo bộ", "Khu BBQ dã ngoại", "Shophouse khối đế & minimart", "Nhà sinh hoạt cộng đồng", "Hệ thống an ninh 24/7"],
    unitTypes: [
      { slug: "can-ho-studio", name: "Căn Studio", bedrooms: 0, bathrooms: 1, constructionArea: "37,0m²", usableArea: "33,0m²", price: "Từ 750 triệu/căn", priceNumber: 750, furnished: true, description: "Studio SkyView", images: ["https://res.cloudinary.com/dthv0nsq/image/upload/q_auto,f_auto/k-home-skyview/noxh-skyview02"] },
      { slug: "can-ho-1-phong-ngu", name: "Căn 1 Phòng Ngủ +", bedrooms: 1, bathrooms: 1, constructionArea: "45,8m²", usableArea: "41,0m²", price: "Từ 990 triệu/căn", priceNumber: 990, furnished: true, description: "1PN+ SkyView", images: ["https://res.cloudinary.com/dthv0nsq/image/upload/q_auto,f_auto/k-home-skyview/noxh-skyview01"] },
      { slug: "can-ho-2-phong-ngu", name: "Căn 2 Phòng Ngủ", bedrooms: 2, bathrooms: 2, constructionArea: "65,3m²", usableArea: "58,5m²", price: "1,35 tỷ – 1,45 tỷ/căn", priceNumber: 1350, furnished: true, description: "2PN SkyView", images: ["https://res.cloudinary.com/dthv0nsq/image/upload/q_auto,f_auto/k-home-skyview/noxh-skyview"] },
    ],
    rating: 4.8,
    floorCount: 12,
    developer: "Kim Oanh Land (Tập đoàn Kim Oanh Group)",
  }
];

export default function handler(_req: VercelRequest, res: VercelResponse) {
  res.setHeader("Cache-Control", "s-maxage=3600, stale-while-revalidate");
  return res.json(DATA);
}
